In [66]:
import numpy as np
import pandas as pd

In [60]:
# country = ['India', 'pakistan', 'USA', 'Nepal', 'Srilanka']
# pd.Series(country)
country = ['Hamza', 'Umar', 'Usman', 'Bilal', 'Shabeer']
pd.Series(country)

0      Hamza
1       Umar
2      Usman
3      Bilal
4    Shabeer
dtype: str

In [61]:
# runs = [13,24,56,78,100]
# runs_ser = pd.Series(runs)
runs = [13,23,45,56,78,90]
runs_per= pd.Series(runs)
runs_per

0    13
1    23
2    45
3    56
4    78
5    90
dtype: int64

In [67]:
# marks = [67,57,89,100]
# subjects= ['maths', 'english', 'science', 'Urdu']
# pd.Series(marks, index=subjects)
marks = [12,34,56,76,78,89]
subjects = ['English', 'Maths', 'Urdu', 'Science','Sindhi', 'Islamiat']
pd.Series(marks, index=subjects)

English     12
Maths       34
Urdu        56
Science     76
Sindhi      78
Islamiat    89
dtype: int64

In [ ]:
# marks = pd.Series(marks, index=subjects, name='Hamza marks')
# marks
marks = pd.Series(marks, index=sun)

maths       67
english     57
science     89
Urdu       100
Name: Hamza marks, dtype: int64

In [36]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'Urdu':100
}
marks_series= pd.Series(marks, name='Hamza k marks')
marks_series

maths       67
english     57
science     89
Urdu       100
Name: Hamza k marks, dtype: int64

In [9]:
marks_series.size

4

In [10]:
marks_series.dtype

dtype('int64')

In [11]:
marks_series.name

'Hamza k marks'

In [12]:
marks_series.is_unique

True

In [13]:
marks_series.index

Index(['maths', 'english', 'science', 'Urdu'], dtype='str')

In [14]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [15]:
marks_series.values

array([ 67,  57,  89, 100])

In [20]:
# subs = pd.read_csv('subs.csv', squeeze=True)
# sub = pd.read_csv('subs.csv', index_col=0).squeeze=('column')
sub = pd.read_csv('subs.csv', index_col=0).squeeze("columns")
print(type(sub))
print(sub.shape)
print(sub)

<class 'pandas.Series'>
(30,)
Date
2022-03-05    48
2022-03-06    57
2022-03-07    40
2022-03-08    53
2022-03-09    63
2022-03-10    45
2022-03-11    36
2022-03-12    72
2022-03-13    65
2022-03-14    58
2022-03-15    41
2022-03-16    69
2022-03-17    77
2022-03-18    50
2022-03-19    44
2022-03-20    39
2022-03-21    61
2022-03-22    55
2022-03-23    48
2022-03-24    70
2022-03-25    66
2022-03-26    52
2022-03-27    47
2022-03-28    60
2022-03-29    49
2022-03-30    73
2022-03-31    68
2022-04-01    56
2022-04-02    42
2022-04-03    38
Name: Subscribers gained, dtype: int64

In [18]:
type(sub)

str

In [46]:
kohli_runs = pd.read_csv('kohli_ipl.csv', index_col='match_no').squeeze("columns")
kohli_runs.head()

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [25]:
kohli_runs.name

'runs'

In [28]:
movies = pd.read_csv('bollywood.csv', index_col='movie').squeeze('columns')

In [36]:
movies.sample(9)

movie
Uri: The Surgical Strike           Vicky Kaushal
Tanhaji                               Ajay Devgn
Zero                              Shah Rukh Khan
Student of the Year 2               Tiger Shroff
Gully Boy                          Ranveer Singh
Good Newwz                          Akshay Kumar
Kalank                                Alia Bhatt
Soni                        Geetika Vidya Ohlyan
Street Dancer 3D                    Varun Dhawan
Name: lead, dtype: str

In [37]:
movies.value_counts()

lead
Akshay Kumar            3
Kangana Ranaut          2
Ranveer Singh           2
Tiger Shroff            2
Vicky Kaushal           1
Vicky Ahuja             1
Anupam Kher             1
Emraan Hashmi           1
Mona Ambegaonkar        1
Geetika Vidya Ohlyan    1
Arshad Warsi            1
Shah Rukh Khan          1
Alia Bhatt              1
Hrithik Roshan          1
Sushant Singh Rajput    1
Sidharth Malhotra       1
Ayushmann Khurrana      1
Ajay Devgn              1
Varun Dhawan            1
Irrfan Khan             1
Name: count, dtype: int64

In [42]:
kohli_runs.sort_values(ascending=False).head(1).values[0]

np.int64(63)

In [44]:
kohli_runs.sort_values(inplace=True)

In [47]:
kohli_runs.head(6)

match_no
1     1
2    23
3    13
4    12
5     1
6     9
Name: runs, dtype: int64

In [49]:
movies.head()

movie
Uri: The Surgical Strike            Vicky Kaushal
Battalion 609                         Vicky Ahuja
The Accidental Prime Minister         Anupam Kher
Why Cheat India                     Emraan Hashmi
Evening Shadows                  Mona Ambegaonkar
Name: lead, dtype: str

In [50]:
movies.sort_index()

movie
Angrezi Medium                               Irrfan Khan
Baaghi 3                                    Tiger Shroff
Bala                                  Ayushmann Khurrana
Battalion 609                                Vicky Ahuja
Chhichhore                          Sushant Singh Rajput
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Good Newwz                                  Akshay Kumar
Gully Boy                                  Ranveer Singh
Housefull 4                                 Akshay Kumar
Kalank                                        Alia Bhatt
Kesari                                      Akshay Kumar
Manikarnika: The Queen of Jhansi          Kangana Ranaut
Marjaavaan                             Sidharth Malhotra
Panga                                     Kangana Ranaut
Simmba                                     Ranveer Singh
Soni                                Geetika Vidya Ohlyan
Street Dancer 3D                            Varun Dhawan
Student of the Year 2                       Tiger Shroff
Tanhaji                                       Ajay Devgn
The Accidental Prime Minister                Anupam Kher
Uri: The Surgical Strike                   Vicky Kaushal
War                                       Hrithik Roshan
Why Cheat India                            Emraan Hashmi
Zero                                      Shah Rukh Khan
Name: lead, dtype: str

In [52]:
kohli_runs.count()

np.int64(30)

In [53]:
sub

Date
2022-03-05    48
2022-03-06    57
2022-03-07    40
2022-03-08    53
2022-03-09    63
2022-03-10    45
2022-03-11    36
2022-03-12    72
2022-03-13    65
2022-03-14    58
2022-03-15    41
2022-03-16    69
2022-03-17    77
2022-03-18    50
2022-03-19    44
2022-03-20    39
2022-03-21    61
2022-03-22    55
2022-03-23    48
2022-03-24    70
2022-03-25    66
2022-03-26    52
2022-03-27    47
2022-03-28    60
2022-03-29    49
2022-03-30    73
2022-03-31    68
2022-04-01    56
2022-04-02    42
2022-04-03    38
Name: Subscribers gained, dtype: int64

In [54]:
sub.sum()

np.int64(1642)

In [57]:
sub.mean()
print(kohli_runs.median())

14.0

In [58]:
print(movies.mode())

0    Akshay Kumar
Name: lead, dtype: str

In [1]:
import pandas as pd 
import numpy as np

In [2]:
sub = pd.read_csv('subs.csv')
vk = pd.read_csv('kohli_ipl.csv')
movies = pd.read_csv('bollywood.csv')

In [5]:
print(vk.median())
print(movies.mode())
# print(sub.std())
print(vk.var())

match_no    15.5
runs        14.0
dtype: float64
                               movie          lead
0                     Angrezi Medium  Akshay Kumar
1                           Baaghi 3           NaN
2                               Bala           NaN
3                      Battalion 609           NaN
4                         Chhichhore           NaN
5                    Evening Shadows           NaN
6                      Fraud Saiyaan           NaN
7                         Good Newwz           NaN
8                          Gully Boy           NaN
9                        Housefull 4           NaN
10                            Kalank           NaN
11                            Kesari           NaN
12  Manikarnika: The Queen of Jhansi           NaN
13                        Marjaavaan           NaN
14                             Panga           NaN
15                            Simmba           NaN
16                              Soni           NaN
17                  Street Dancer 3D           NaN
18             Student of the Year 2           NaN
19                           Tanhaji           NaN
20     The Accidental Prime Minister           NaN
21          Uri: The Surgical Strike           NaN
22                               War           NaN
23                   Why Cheat India           NaN
24                              Zero           NaN
match_no     77.500000
runs        272.943678
dtype: float64

In [6]:
sub.min()

Date                  2022-03-05
Subscribers gained            36
dtype: object

In [8]:
sub.max()

Date                  2022-04-03
Subscribers gained            77
dtype: object

In [9]:
vk.describe()

        match_no       runs
count  30.000000  30.000000
mean   15.500000  18.233333
std     8.803408  16.521007
min     1.000000   0.000000
25%     8.250000   5.250000
50%    15.500000  14.000000
75%    22.750000  24.500000
max    30.000000  63.000000

In [11]:
x = pd.Series([12,34,45,56,78,89,90])
x[2]

np.int64(45)

In [18]:

bollywood = pd.read_csv('bollywood.csv', index_col=0).squeeze("columns")

In [71]:
bollywood.iloc[3]

movie    Why Cheat India
lead       Emraan Hashmi
Name: 3, dtype: str

In [23]:
bollywood = pd.read_csv('bollywood.csv')

In [25]:
bollywood.iloc[0:5]

                           movie              lead
0       Uri: The Surgical Strike     Vicky Kaushal
1                  Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister       Anupam Kher
3                Why Cheat India     Emraan Hashmi
4                Evening Shadows  Mona Ambegaonkar

In [28]:
bollywood.iloc[::4]

                       movie              lead
0   Uri: The Surgical Strike     Vicky Kaushal
4            Evening Shadows  Mona Ambegaonkar
8                     Simmba     Ranveer Singh
12                    Kalank        Alia Bhatt
16               Housefull 4      Akshay Kumar
20                   Tanhaji        Ajay Devgn
24            Angrezi Medium       Irrfan Khan

In [30]:
vk.head()

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [31]:
vk = pd.read_csv('kohli_ipl.csv', index_col=0).squeeze("columns")

In [32]:
vk[[1,3,4]]

match_no
1     1
3    13
4    12
Name: runs, dtype: int64

In [35]:
bollywood.iloc[[1,4,5]]

             movie                  lead
1    Battalion 609           Vicky Ahuja
4  Evening Shadows      Mona Ambegaonkar
5             Soni  Geetika Vidya Ohlyan

In [37]:
marks_series

maths       67
english     57
science     89
Urdu       100
Name: Hamza k marks, dtype: int64

In [45]:
marks_series[1] = 100
marks_series['english'] = 100
marks_series

maths       67
english    100
science     89
Urdu       100
1          100
Name: Hamza k marks, dtype: object

In [46]:
marks_series = marks_series.drop(marks_series.index[4])
marks_series

maths       67
english    100
science     89
Urdu       100
Name: Hamza k marks, dtype: object

In [47]:
marks_series['sst'] = 92
marks_series

maths       67
english    100
science     89
Urdu       100
sst         92
Name: Hamza k marks, dtype: object

In [50]:
runs = [13,24,56,78,100]
runs_per = pd.Series(runs)
runs_per

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [53]:
# runs_per[[0:1]] = [70,75]
runs_per[[0, 3]] = [15, 80]
runs_per

0     15
1     24
2     56
3     80
4    100
dtype: int64

In [54]:
runs_per[[0,3,4]] = [0,0,0]
runs_per

0     0
1    24
2    56
3     0
4     0
dtype: int64

In [60]:

len(vk)
print(type(vk))
print(dir(vk))
print(sorted(vk))
print(min(vk))
print(max(vk))

<class 'pandas.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_attrs', '_binop', '_can_hold_na', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_ixs', '_logical_func', '_logical_method', '_map_values', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_module_source', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'between', 'between_time', 'bfill', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']
[0, 0, 1, 1, 2, 3, 3, 4, 9, 9, 10, 10, 11, 12, 13, 15, 15, 21, 21, 21, 21, 23, 25, 26, 32, 34, 38, 50, 54, 63]
0
63

In [63]:
marks_series
list(marks_series)
dict(marks_series)

{'maths': 67, 'english': 100, 'science': 89, 'Urdu': 100, 'sst': 92}

In [65]:
print(marks_series)
print(dict(marks_series))
list(marks_series)

maths       67
english    100
science     89
Urdu       100
sst         92
Name: Hamza k marks, dtype: object
{'maths': 67, 'english': 100, 'science': 89, 'Urdu': 100, 'sst': 92}

[67, 100, 89, 100, 92]

In [68]:
print('good')

good

In [69]:
print('jojo')

jojo

In [70]:
'''Hamza'''

'Hamza'